name: build

on:
  push:
    paths:
      - ".github/workflows/build.yml"
      - 'Changes'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: crazy-max/ghaction-docker-buildx@v3
        with:
          buildx-version: v0.4.1
      - run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
      - run: git submodule update --init
      - run: |
          docker buildx build \
            --push \
            --platform=linux/arm64,linux/amd64 \
            -f=docker/alpine/Dockerfile \
            -t=${{ github.repository }} \
            .
